Documentation:
  - docs/*
  - docs/**/*
  - ./*.rst
  - ./*.md

Python:
  - brainstat/*
  - brainstat/**/*

MATLAB:
  - brainstat_matlab/*
  - brainstat_matlab/**/*

Github:
  - .github/*
  - .github/**/*
