# Trigger on all branches, only for changes in the matlab directory.
trigger:
  branches:
    include:
      - '*'
  paths:
      include:
        - matlab

# Set languages and operating system.
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
#    Python 3.6:
#      implementation_language: 'python'
#      implementation_version: '3.6'
#    Python 3.7:
#      implementation_language: 'python'
#      implementation_version: '3.7'
    MATLAB 2020a:
      implementation_language: 'matlab'
      implementation_version: 'R2020a'

steps:
  # Install Python/MATLAB
  - task: UsePythonVersion@0
    condition: eq(variables.implementation_language, 'python')
    inputs:
      versionSpec: $(implementation_version)
    displayName: 'Use Python $(implementation_version)'
  - task: InstallMATLAB@0
    condition: eq(variables.implementation_language, 'matlab')
    inputs:
      release: $(implementation_version)
    displayName: 'Use MATLAB $(implementation_version)'

  # Lint Python
  - script: |
      python -m pip install flake8
      flake8 --select E101,E117,E125,E302,W191,W291,W293 ./brainstat 
    displayName: 'Run Python lint tests'
    condition: eq(variables.implementation_language, 'python')
  # Run MATLAB unit tests. 
  - task: RunMATLABTests@0
    condition: eq(variables.implementation_language, 'matlab')
    displayName: 'Run MATLAB unit tests.'
    inputs:
      sourceFolder: 'matlab'
