# Trigger on all branches, trigger:
  batch: true
  branches:
    include:
      - '*'

# Set languages and operating system.
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    MATLAB 2020a:
      implementation_version: 'latest'

steps:
  - task: InstallMATLAB@0
    inputs:
      release: $(implementation_version)
    displayName: 'Use MATLAB $(implementation_version)'

  - name: Download unit test data
    run: |
      git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
      git fetch origin test-data

  - task: RunMATLABTests@0
    displayName: 'Run MATLAB unit tests.'
    inputs:
      sourceFolder: 'brainstat_matlab'
