language: python

os:
  - linux

addons:
  apt:
    packages:
      - flake8

install:
  - env | grep -v "encrypted" | LC_ALL=C sort
  - lscpu || sysctl hw

script:
  - flake8 --select E101,E117,E125,E302,W191,W291,W293 .

