trigger:
- main

# Set languages.
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python 3.7:
      implementation_version: '3.7'
      implementation_language: 'python'
#    MATLAB R2020a:
#      implementation_language: 'matlab'
#      implementation_version: 'latest'

steps:
  # Install Python/MATLAB
  - task: UsePythonVersion@0
#    condition: eq($(implementation_language), 'python')
    inputs:
      versionSpec: $(implementation_version)
    displayName: 'Use Python $(implementation_version)'
#  - task: InstallMATLAB@0
#    condition: eq($(implementation_language), 'matlab')
#    inputs:
#      release: $(implementation_version)
#    displayName: 'Use MATLAB $(implementation_version)'

  # Lint Python
  - script: |
      python -m pip install flake8
      flake8 surfstat/python
    displayName: 'Run lint tests'
    condition: eq(variables.implementation_language, 'python')
  # Run MATLAB unit tests. 
#  - task: RunMATLABTests@0
#    condition: eq($(implementation_language), 'matlab')
#    inputs:
#      sourceFolder: 'matlab'