name: MATLAB CI

on: 
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install numpy
        git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
        git fetch origin test-data
        git checkout origin/test-data -- extern/test-data
        git reset extern/test-data
    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v0
    - name: Run tests 
      uses: matlab-actions/run-tests@v0
      with:
        SourceFolder: brainstat_matlab