name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install libgl
      run: apt-get install libgl1-mesa-glx
    - name: Checkout Commit
      uses: actions/checkout@v2
    - name: Build the Docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"