name: Publish Python to PyPi-test

on: push

jobs:
  python_setup:
    name: Set up Python.
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
  install_brainstat:
    - name: Install brainstat
      run: >-
        python -m
        pip install
        build
        --user
  build_wheel:
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
  publish:
    - name: Publiish distribution to PyPi-test
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
